{application,kvs_service,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{kvs_service_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[dbase,kvs,lib_dbase,lib_kvs]},
              {licenses,["Apache-2.0"]},
              {links,[]}]}.
